import Footer from "@/components/common/Footer/footer";
import Header from "@/components/common/Header/header";
import "./globals.css";

export const metadata = {
  title: "Upchar | A Medical Product",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <Header />
        <main className="flex-1">{children}</main>
        <Footer/>
      </body>
    </html>
  );
}
